### ISSUE TITLE
auctionのendTime, maxEndTimeが遠すぎる将来時刻になっている問題の調査・修正

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/jpyx#124]
https://github.com/lcnem/botany/pull/136#discussion_r743343109

**Comment by KimuraYu45z** [comment]
x/auction/types/auctions.go
の27行目ですが、

```
var DistantFuture = time.Date(9000, 1, 1, 0, 0, 0, 0, time.UTC)
```

とあり、

これを

x/auction/keeper/auctions.goの21行目で使用していることから、正常な挙動だと思われました。

調査すべきは、これが異常かどうかではなく、

- KavaでもdistantFuture使っているで間違いないか再確認（v0.13.0）
- 「DistantFuture」で作成されたauctionが、どのように終了するのか

だと思いました。

**Comment by YasunoriMATSUOKA** [comment]
@KimuraYu45z @Senna46 
以下プルリクで、auction自体は成立しているように見えたので、このIssueは、そういう仕様であると判断して、クローズしてよいかなと思いました。クローズしておくので、もし何かあれば、コメントください。
https://github.com/lcnem/botany/pull/143
