### ISSUE TITLE
Get the penalty cost when bidders don't pay the full amount through API

### ISSUE THREAD

**Issue by yukiwaki** [lcnem/jpyx#252]
We need to show that they were under penalty and they did pay the penalty cost when bidders don't pay the full amount on the payment period.
how can we know if they didn't pay the full amount and pay the penalty cost, after the payment period and penalty amount?

**Comment by mkXultra** [comment]
If payment is not made, the paid_amount will be forfeited.
It is usually called "Deposit

**Comment by mkXultra** [comment]
It can be obtained using existing APIs.
