### ISSUE TITLE
[優先度 小]テストコードにkavaとusdxの表記が大量に残っているので修正したい

### ISSUE THREAD

**Issue by Senna46** [lcnem/jpyx#60]
正規表現置換で換えていく

参考
- プロジェクト名（LCNEM内での呼称）
KAVA -- JPYX
- ステーブルコイントークン
USDX -- JPYX
- ガバナンストークン
kava (KAVA) -- jsmn (Jasmine)

**Comment by Tomosuke0930** [comment]
cdpとinsentiveに大量に残っているkava,usdxをjsmn,jpyxに変更する
https://cauchye.slack.com/archives/CKV987JSW/p1630392294125800

**Comment by Tomosuke0930** [comment]
修正が必要なファイル　cdp ファイル編

cdp/keeper/
- [ ] cdps_test.go
- [ ] deposit_test.go
- [ ] draw_test.go
- [ ] integration_test.go
- [ ] keeper_bench_test.go
- [ ] seize_test.go

cdp/types/
- [ ] cdp_test.go
- [ ] params_test.go

cdp/
- [ ] abi_test.go
- [ ] integration_test.go

**Comment by KimuraYu45z** [comment]
↑これファイルリスト書いてる時点で正規表現一括置換が伝わってないですね
誰かまた後で伝えておいてください

完了
