### ISSUE TITLE
[優先度 中]AccAddressの変更

### ISSUE THREAD

**Issue by Senna46** [lcnem/jpyx#61]
x/auction/types/auctions_test.go

```
	testAccAddress1         = "jpyx1qcfdf69js922qrdr4yaww3ax7gjml6pd39p8lj"
	testAccAddress2         = "jpyx1pdfav2cjhry9k79nu6r8kgknnjtq6a7rcr0qlr"
```

AccAddressをcosmos-client-tsなどで生成したまともな値に変更する

**Comment by Senna46** [comment]
https://github.com/cosmos-client/cosmos-client-ts
src/rest/cosmos/bank/bank.spec.ts などがテストコード

**Comment by Tomosuke0930** [comment]
@Senna46 
■確認
こちらの業務としてはx/auction/types/auctions_test.goにあるようなtestAccAddressの値をcosmos-client-tsで生成した値に変換する。そのcosmos-client-tsの値の例としてsrc/rest/cosmos/bank/bank.spec.tsファイルを教えていただいたという認識でよろしいでしょうか？

**Comment by Senna46** [comment]
@Tomosuke0930 
spec.tsはテストコードを書いているファイルになるので、bank.spec.ts以外にもいくつかのspec.tsファイルを使って新しいKeyを作るという作業でした。

ですが、、Cosmoscanにすでにキーを作成する機能を追加していたのでこちらで作る方がスムーズかと思います。
https://github.com/lcnem/cosmoscan/blob/main/projects/cosmoscan/src/app/keys/create/create.component.ts

http://b.test.jpyx.lcnem.net/
一度Cosmoscanを触ってみて、Keyの作成やってみてください。詳しい内容は省くので操作に困ったらNeWorkの部屋にでも来てもらえると！

**Comment by Tomosuke0930** [comment]
現状こちらのエラーで詰まっております。

Running tool: /Users/tom/.goenv/versions/1.16.4/bin/go test -timeout 30s -run ^TestDebtAuctionValidate$ github.com/lcnem/jpyx/x/auction/types

# github.com/keybase/go-keychain
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here
--- FAIL: TestDebtAuctionValidate (0.00s)
    /Users/Tom/Desktop/Works/lcnem/cosmos/jpyx/x/auction/types/auctions_test.go:268: 
        	Error Trace:	auctions_test.go:268
        	Error:      	An error is expected but got nil.
        	Test:       	TestDebtAuctionValidate
        	Messages:   	invalid corresponding debt
FAIL
FAIL	github.com/lcnem/jpyx/x/auction/types	0.373s
FAIL
